### ISSUE TITLE
Allow projects consuming @barnardos/components to define component's colours

### ISSUE THREAD

**Issue by joelcarr** [barnardos/design-system#598]
_As a project consuming `@barnardos/components` package
I want to be able to define the colours of the components
So that I can establish my brand onto the components_

## Description

As a project consuming the design system where colours need to be unique from Barnardo's, I want to be able to define the colours used for a component. 

When @jeddy3 and I have talked about this before, we assumed the project consuming the `@barnardos/components` package would have to write CSS that will override the package's styles.

For example:

```CSS
/* ./my-project/src/components/Submit/index.css */
@import "@barnardos/components/src/components/Submit/index.css";

.Submit {
  background-color: var(--purple);
}
```

This will compile to:

```CSS
.Submit {
  background-color: #6aa300; /* var(--green) */
}

.Submit {
  background-color: #6e2066; /* var(--purple) */
}
```

Using CSS's `@import` feature, a consuming project is able to define its own variables for the components to use. We could have component specific variables which should a consuming project can override without having to rewrite the rules.

For example:

```CSS
/* ./my-project/src/components/Submit/index.css */
@import "@barnardos/components/src/components/Submit/index.css";

:root {
  --Submit-color: var(--purple);
}
```

Which should compile down to:

```CSS
.Submit {
  background-color: #6e2066; /* var(--Submit-color) */
}
```
